### ISSUE TITLE
Notifications firing incorrectly

### ISSUE THREAD

**Issue by gshutler** [czarneckid/hipchat-api#3]
I'm not sure if there's anything you can do but since I changed my `rooms_message` call to this:

https://github.com/gshutler/hatchet-hipchat/blob/5fff28bcd03017bf573a3663e355e17bbb7f8ced/lib/hatchet-hipchat/hipchat_appender.rb#L52

The channel has been notified of messages. Looking through you're code I'm pretty sure I'm passing the parameter through correctly and consulting their API documentation I think the correct value is being sent.

Have you got any ideas what might be causing this?

**Comment by czarneckid** [comment]
What do you mean the notifications are firing incorrectly? Are the messages coming in the wrong order in the room? Are all the messages making it into the room correctly?

**Comment by gshutler** [comment]
They are making it into the room as expected but we're getting "toaster" notifications for them when I wouldn't expect to be getting them.

**Comment by czarneckid** [comment]
OK, so their API isn't respecting the notify parameter? That is odd. 

I tested locally in our HipChat room using the AIR client under OS X and didn't notice anything wrong when notify was sent as 0. My call was as follows:

``` ruby
hipchat.rooms_message(8675309, 'HipChat API', 'This is a test message for @david for toaster notifications testing', 0, 'random', 'text')
```

**Comment by gshutler** [comment]
Yeah, that's the problem I'm experiencing. The only thing different to your call is that I'm using the room name and the text includes an emoticon. Could that be something to do with it?

**Comment by czarneckid** [comment]
I was able to reproduce that issue as well. It turns out in my call above I didn't have any of the "Notify me by" settings checked on. Once I checked them all on, I did an API call as above and saw the "toaster" notification as well. As you say, I wouldn't expect that to happen if notify is 0. I'm not sure I can do anything about this in the API client however, so I'll let you notify HipChat about the issue on their support forums, http://help.hipchat.com/.

**Comment by gshutler** [comment]
Great. Thanks very much for your help.

**Comment by powdahound** [comment]
A little more detail: Our client isn't respecting the notify parameter on message_format=text messages, but we'll that that fixed in a minor update shortly.

**Comment by gshutler** [comment]
Awesome. Thank you.
