### ISSUE TITLE
Instruction on how to change DEFAULT_TIMEOUT

### ISSUE THREAD

**Issue by zbuckholz** [czarneckid/hipchat-api#8]
I noticed in the code there is a three second default timeout.

How can I pass a new value when initializing the object?

I tried the following but it failed:

hipchat_api = HipChat::API.new('private_token',default_timeout=20)

Please provide an example

Thanks
Zach

**Comment by czarneckid** [comment]
https://github.com/czarneckid/hipchat-api/blob/master/spec/hipchat-api_spec.rb#L31-L35
